SELECT "user_name",
       SUM(CASE WHEN LOWER("result_code") LIKE '%retry%' OR LOWER("result_code") LIKE '%sch%' THEN 1 ELSE 0 END) AS "retry",
       SUM(CASE WHEN LOWER("result_code") LIKE '%sold%' THEN 1 ELSE 0 END) AS "sold",
       SUM(CASE WHEN LOWER("result_code") LIKE '%aca%' AND LOWER("result_code") NOT LIKE '%sold%' THEN 1 ELSE 0 END) AS "aca",
       SUM(CASE WHEN LOWER("result_code") LIKE '%appt%' THEN 1 ELSE 0 END) AS "appt",
       SUM(CASE WHEN LOWER("result_code") LIKE '%ans%' OR LOWER("result_code") LIKE '%amlm%' THEN 1 ELSE 0 END) AS "answering_machine",
       SUM(CASE WHEN LOWER("result_code") LIKE '%bad%' THEN 1 ELSE 0 END) AS "bad_num",
       SUM(CASE WHEN LOWER("result_code") LIKE '%broke%' OR LOWER("result_code") LIKE '%$%' OR LOWER("result_code") LIKE '%money%' THEN 1 ELSE 0 END) AS "no_money",
       SUM(CASE WHEN LOWER("result_code") LIKE '%blank%' OR LOWER("result_code") LIKE '%dead%' THEN 1 ELSE 0 END) AS "blank",
       SUM(CASE WHEN LOWER("result_code") LIKE '%bomb%' THEN 1 ELSE 0 END) AS "bombarded",
       SUM(CASE WHEN LOWER("result_code") LIKE '%cb%' OR LOWER("result_code") LIKE '%call back%' OR LOWER("result_code") LIKE '%callback%' OR LOWER("result_code") LIKE '%c / b%' OR LOWER("result_code") LIKE '%call_back%' THEN 1 ELSE 0 END) AS "callback",
       SUM(CASE WHEN LOWER("result_code") LIKE '%disc%' THEN 1 ELSE 0 END) AS "disconnect",
       SUM(CASE WHEN LOWER("result_code") LIKE 'dn%' THEN 1 ELSE 0 END) AS "dnc",
       SUM(CASE WHEN LOWER("result_code") LIKE '%dup%' THEN 1 ELSE 0 END) AS "duplicate",
       SUM(CASE WHEN LOWER("result_code") LIKE '%req%' THEN 1 ELSE 0 END) AS "denies_req",
       SUM(CASE WHEN LOWER("result_code") LIKE '%dental%' THEN 1 ELSE 0 END) AS "dental",
       SUM(CASE WHEN LOWER("result_code") LIKE 'em%' AND LOWER("result_code") NOT LIKE '%employ%' THEN 1 ELSE 0 END) AS "email",
       SUM(CASE WHEN LOWER("result_code") LIKE '%employ%' THEN 1 ELSE 0 END) AS "employer",
       SUM(CASE WHEN LOWER("result_code") LIKE '%ghost%' THEN 1 ELSE 0 END) AS "ghost",
       SUM(CASE WHEN LOWER("result_code") LIKE '%give%' THEN 1 ELSE 0 END) AS "give_up",
       SUM(CASE WHEN LOWER("result_code") LIKE '%group%' THEN 1 ELSE 0 END) AS "grouped",
       SUM(CASE WHEN LOWER("result_code") LIKE '%hang%' OR LOWER("result_code") LIKE '%hung%' OR LOWER("result_code") = 'h/up' THEN 1 ELSE 0 END) AS "hang_up",
       SUM(CASE WHEN LOWER("result_code") LIKE '%happy%' OR LOWER("result_code") LIKE '%hpy%' THEN 1 ELSE 0 END) AS "happy",
       SUM(CASE WHEN LOWER("result_code") LIKE '%has%' OR LOWER("result_code") LIKE '%other%' OR LOWER("result_code") = 'h / c' OR LOWER("result_code") LIKE '%unins%' THEN 1 ELSE 0 END) AS "has_other",
       SUM(CASE WHEN LOWER("result_code") LIKE 'health%' OR LOWER("result_code") LIKE 'nq%' THEN 1 ELSE 0 END) AS "health",
       SUM(CASE WHEN LOWER("result_code") LIKE '%incent%' THEN 1 ELSE 0 END) AS "incentive",
       SUM(CASE WHEN LOWER("result_code") LIKE '%low%' THEN 1 ELSE 0 END) AS "low_income",
       SUM(CASE WHEN LOWER("result_code") LIKE '%med%' OR LOWER("result_code") LIKE '%mpo%' THEN 1 ELSE 0 END) AS "medicare",
       SUM(CASE WHEN LOWER("result_code") LIKE '%major%' THEN 1 ELSE 0 END) AS "major_condition",
       SUM(CASE WHEN LOWER("result_code") LIKE '%nc%' OR LOWER("result_code") LIKE '%contact%' OR LOWER("result_code") = 'n / a' OR LOWER("result_code") LIKE '%left%' OR LOWER("result_code") LIKE 'l /%' OR LOWER("result_code") LIKE 'n /%' OR LOWER("result_code") LIKE 'no s%' THEN 1 ELSE 0 END) AS "no_contact",
       SUM(CASE WHEN LOWER("result_code") LIKE '%like%' THEN 1 ELSE 0 END) AS "no_likey",
       SUM(CASE WHEN LOWER("result_code") LIKE '%int%' OR LOWER("result_code") LIKE 'ni%' OR LOWER("result_code") = 'n / i' OR LOWER("result_code") LIKE '%need%' OR LOWER("result_code") LIKE 'ready%' THEN 1 ELSE 0 END) AS "not_interested",
       SUM(CASE WHEN LOWER("result_code") LIKE '%old%' AND LOWER("result_code") NOT LIKE '%em%' THEN 1 ELSE 0 END) AS "too_old",
       SUM(CASE WHEN LOWER("result_code") LIKE '%young%' THEN 1 ELSE 0 END) AS "too_young",
       SUM(CASE WHEN LOWER("result_code") LIKE '%obama%' THEN 1 ELSE 0 END) AS "obamacare",
       SUM(CASE WHEN LOWER("result_code") LIKE '%list%' THEN 1 ELSE 0 END) AS "off_list",
       SUM(CASE WHEN LOWER("result_code") LIKE '%out%' THEN 1 ELSE 0 END) AS "out",
       SUM(CASE WHEN LOWER("result_code") LIKE '%preg%' THEN 1 ELSE 0 END) AS "pregnant",
       SUM(CASE WHEN LOWER("result_code") LIKE '%pres%' THEN 1 ELSE 0 END) AS "presented",
       SUM(CASE WHEN LOWER("result_code") LIKE '%short%' THEN 1 ELSE 0 END) AS "short_term",
       SUM(CASE WHEN LOWER("result_code") LIKE '%sick%' OR LOWER("result_code") LIKE '%unhealth%' THEN 1 ELSE 0 END) AS "unhealthy",
       SUM(CASE WHEN LOWER("result_code") LIKE '%snooze%' THEN 1 ELSE 0 END) AS "snooze",
       SUM(CASE WHEN LOWER("result_code") LIKE '%spanish%' THEN 1 ELSE 0 END) AS "spanish",
       SUM(CASE WHEN LOWER("result_code") LIKE '%transfer%' THEN 1 ELSE 0 END) AS "transfer",
       SUM(CASE WHEN LOWER("result_code") LIKE '%tri%' THEN 1 ELSE 0 END) AS "tricare",
       SUM(CASE WHEN LOWER("result_code") LIKE '%wrong%' OR LOWER("result_code") LIKE '%w#%' THEN 1 ELSE 0 END) AS "wrong_num",
       SUM(CASE WHEN LOWER("result_code") LIKE '%webby%' THEN 1 ELSE 0 END) AS "webby",
       SUM(CASE WHEN LOWER("result_code") LIKE '%unresolve%' THEN 1 ELSE 0 END) AS "unresolved",
       SUM(CASE WHEN LOWER("result_group") LIKE '%callback%' THEN 1 ELSE 0 END) AS "contact_callback",
       SUM(CASE WHEN LOWER("result_group") LIKE '%negative%' THEN 1 ELSE 0 END) AS "contact_negative",
       SUM(CASE WHEN LOWER("result_group") LIKE '%positive%' THEN 1 ELSE 0 END) AS "contact_positive",
       SUM(CASE WHEN LOWER("result_group") LIKE '%info%' THEN 1 ELSE 0 END) AS "contact_sendInfo",
       SUM(CASE WHEN LOWER("result_group") LIKE '%no c%' THEN 1 ELSE 0 END) AS "no_contact_group",
       SUM(CASE WHEN LOWER("result_group") LIKE '%reach%' THEN 1 ELSE 0 END) AS "unreachables_group"

FROM public.vanillasoft_results_prod vrp
WHERE "call_date_time_utc" >= NOW() - INTERVAL '90 days'

GROUP BY "user_name";